POST http://localhost:8000/api/student/add HTTP/1.1
content-type: application/json

{
    "id": "xx22iasddd",
    "firstName": "Briaasn",
    "lastName": "Lisondasra",
    "gender": "Mas",
    "contactNumber" : "09154516as111",
    "emailAddress": "test@gmailas.com",
    "dateOfBirth": "06/14/2as001",
    "level": "Exaspert"
}


###
POST http://localhost:8000/api/instructor/add HTTP/1.1
content-type: application/json

{
    "user_id": "z6Z88m3EHZZs3BPAI9L4q98lRWD3",
    "rating": "5",
    "description": "tiktok",
    "dance_specialty": "hiphip"
}

###
GET http://localhost:8000/api/student/me/z6Z88m3EHZZs3BPAI9L4q98lRWD3 HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/instructor/profile/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZ2JxcHlncXo3MlFWQWlkbTkwbHhxOW96OWk5MiIsImlhdCI6MTY4MjExODU0OCwiZXhwIjoxNjgyMjA0OTQ4fQ.x80K6yqH0Mm4Fq27JYMSBzMxXv7G32XUBN5MmfMbn_U



###
GET http://localhost:8000/api/student/me/z6Z88m3EHZZs3BPAI9L4q98lRWD3 HTTP/1.1
content-type: application/json

###
POST http://localhost:8000/api/dance-class/add/live HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiejZaODhtM0VIWlpzM0JQQUk5TDRxOThsUldEMyIsImlhdCI6MTY4MTM1NzQ5MiwiZXhwIjoxNjgxNDQzODkyfQ.QJzdw_gq3TGK-uyDhDzqYnTpSFu1tv2ZRlmmChUbGHY

{
    "instructor_id": 24,
    "dance_name": "Cupid Tiktok",
    "dance_song": "Cupid",
    "dance_difficulty": "Hard",
    "date": "06/14/2001",
    "location": "Talamban",
    "price": "400",
    "description": "Forda Tiktok",
    "student_limit": 20,
    "mode_of_payment": "Paypal",
    "account_name": "Brian",
    "account_number": "12345"
}

###
GET http://localhost:8000/api/dance-class/live/all HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/instructor/xx22id HTTP/1.1
content-type: application/json


# const {dance_name, dance_genre, dance_song, dance_difficulty, date,location,price,description,student_limit, mode_of_payment,account_name,account_number} = newDanceClass;
