POST http://localhost:8000/api/student/add HTTP/1.1
content-type: application/json

{
    "id": "xx22iasddd",
    "firstName": "Briaasn",
    "lastName": "Lisondasra",
    "gender": "Mas",
    "contactNumber" : "09154516as111",
    "emailAddress": "test@gmailas.com",
    "dateOfBirth": "06/14/2as001",
    "level": "Exaspert"
}


###
POST http://localhost:8000/api/instructor/add HTTP/1.1
content-type: application/json

{
    "user_id": "z6Z88m3EHZZs3BPAI9L4q98lRWD3",
    "rating": "5",
    "description": "tiktok",
    "dance_specialty": "hiphip"
}

###
GET http://localhost:8000/api/student/me/DfTmRA5ftbQooYwlwiGXUcrzQlZ2 HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/instructor/profile/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZ2JxcHlncXo3MlFWQWlkbTkwbHhxOW96OWk5MiIsImlhdCI6MTY4MjExODU0OCwiZXhwIjoxNjgyMjA0OTQ4fQ.x80K6yqH0Mm4Fq27JYMSBzMxXv7G32XUBN5MmfMbn_U

###
GET http://localhost:8000/api/instructor/55/live HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRGZUbVJBNWZ0YlFvb1l3bHdpR1hVY3J6UWxaMiIsImlhdCI6MTY4MzMyNTExNiwiZXhwIjoxNjgzNDExNTE2fQ.VjGR24vOHIIU0upwvSiVHVSGWKMEUX1kDCIN0-tNq4c



###
GET http://localhost:8000/api/student/me/z6Z88m3EHZZs3BPAI9L4q98lRWD3 HTTP/1.1
content-type: application/json

###
POST http://localhost:8000/api/dance-class/add/live HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMHVmMHVMaThSSFBkZHhxQUxKNVVjd20yeXpuMiIsImlhdCI6MTY4MjMyNDk3MiwiZXhwIjoxNjgyNDExMzcyfQ.eCwAPP80-HpfIVRPKvBulrIyhlG7o-u5e6X-FQMKkW4

{
    "instructor_id": 24,
    "dance_name": "Cupid Tiktok",
    "dance_song": "Cupid",
    "dance_difficulty": "Hard",
    "date": "2024-01-01",
    "location": "Talamban",
    "price": "400",
    "description": "Forda Tiktok",
    "student_limit": 20,
    "mode_of_payment": "Paypal",
    "account_name": "Brian",
    "account_number": "12345"
}

###
GET http://localhost:8000/api/dance-class/live/all HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/dance-class/recorded/all HTTP/1.1
content-type: application/json


###
GET http://localhost:8000/api/instructor/all HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/instructor/DfTmRA5ftbQooYwlwiGXUcrzQlZ2 HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/student/30/classes HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/instructor/54/recorded HTTP/1.1
content-type: application/json

###

GET http://localhost:8000/api/dance-class/live/11/students HTTP/1.1
content-type: application/json

###
POST http://localhost:8000/api/attendance/class/10/ HTTP/1.1
content-type: application/json

{
    "student_id": 30
}

###
GET http://localhost:8000/api/attendance/class/10/generate HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/api/dance-class/5/attendance HTTP/1.1
content-type: application/json

# const {dance_name, dance_genre, dance_song, dance_difficulty, date,location,price,description,student_limit, mode_of_payment,account_name,account_number} = newDanceClass;

###
POST http://localhost:8000/api/rating/instructor/54/ HTTP/1.1
content-type: application/json

{
    "student_id": 29,
    "rating": 5
}

###
GET http://localhost:8000/api/like/class/10 HTTP/1.1
content-type: application/json